### ISSUE TITLE
Test project in windows

### ISSUE THREAD

**Issue by anyong** [lennym/i18n-future#2]
Using the same setup as the test project, [this line](https://github.com/lennym/i18n-future-test-project/blob/master/server/routes/home.js#L10) throws an error on Windows 8.1:

```
c:\dev\test-project\node_modules\i18n-future\lib\backends\fs.js:25
    rgx = new RegExp(rgx);
          ^
SyntaxError: Invalid regular expression: /locales\([a-zA-Z-_]*)\([a-zA-Z-_]*).json/: Unmatched ')'
```

It works if I do:

    path: path.join(__dirname, '..\..\locales\__lng__\__ns__.json'),

But then I just see the key names in the template.

**Comment by lennym** [comment]
Resolved by #3
